### ISSUE TITLE
登入顯示Message: element not interactable

### ISSUE THREAD

**Issue by zxcjeff32211** [opabravo/zuvio#1]
使用正修科技大學帳號密碼登入顯示下列Message: element not interactable
  (Session info: headless chrome=90.0.4430.85)請問該如何解決呢?

**Comment by zxcjeff32211** [comment]
會是因為正修科技大學的Zuvio登入是要開啟google登入帳密?

**Comment by opabravo** [comment]
> 使用正修科技大學帳號密碼登入顯示下列Message: element not interactable
> (Session info: headless chrome=90.0.4430.85)請問該如何解決呢?

麻煩截圖錯誤畫面~

**Comment by opabravo** [comment]
> 會是因為正修科技大學的Zuvio登入是要開啟google登入帳密?

能否詳細說明何謂"開啟google登入帳密"呢，謝謝

**Comment by zxcjeff32211** [comment]
> > 使用正修科技大學帳號密碼登錄顯示消息：元素不可交互
> > （會話信息：headless chrome = 90.0.4430.85）請問該如何解決呢？
> 
> 麻煩截圖錯誤畫面〜

![未命名](https://user-images.githubusercontent.com/83383578/116963508-9a365780-acdb-11eb-98eb-286d5f21430c.png)

**Comment by zxcjeff32211** [comment]
> > 會是因為正修科技大學的Zuvio登錄是要開啟google登錄帳密嗎？
> 
> 能否詳細說明何謂“開啟google登錄帳密”呢，謝謝

![未命名2](https://user-images.githubusercontent.com/83383578/116963640-fb5e2b00-acdb-11eb-89b1-fbb83e33218c.png)
![擷取3](https://user-images.githubusercontent.com/83383578/116963644-fc8f5800-acdb-11eb-8062-1f8433574c32.PNG)
我個人猜測是不是如上圖因為Zuvio跟學校有合作會引導到Google登入介面才會這樣。

**Comment by zxcjeff32211** [comment]
> > 會是因為正修科技大學的Zuvio登錄是要開啟google登錄帳密嗎？
> 
> 能否詳細說明何謂“開啟google登錄帳密”呢，謝謝

![未命名2](https://user-images.githubusercontent.com/83383578/116963807-70c9fb80-acdc-11eb-87ce-2ed6ae6a9d42.png)
![擷取3](https://user-images.githubusercontent.com/83383578/116963809-732c5580-acdc-11eb-9490-51137d45dc2d.PNG)
如上圖Zuvio跟正修有合作引導登入用Google介面，才會引發錯誤嗎?

**Comment by opabravo** [comment]
謝謝您的回報
已新增手動登入帳號的功能
請至 https://github.com/opabravo/zuvio/releases
下載最新版本

如有任何後續的建議以及回報，歡迎提出!

**Comment by zxcjeff32211** [comment]
> 謝謝您的回報
> 已新增手動登錄帳號的功能
> 請至https://github.com/opabravo/zuvio/releases
> 下載最新版本
> 
> 如有任何後續的建議以及回報，歡迎提出！

目前1.1可以用了，很謝謝您辛苦了!
